name: Gacha
version: 1.3
api-version: 1.17
description: gacha.
author: kubotan
main: space.gorogoro.gacha.Gacha

commands:
  gacha:
    description: Commands to manage your gacha
    aliases: [gatya]
    usage: |
      Use /help gacha [subcommand] for more information
      /<command> list - List all gacha
      /<command> modify <gacha_name> - Modify a gacha
      /<command> delete <gacha_name> - Delete a gacha
      /<command> ticket <player_name> - Issue a ticket
  gacha list:
    description: List all gacha
    aliases: [gacha l]
    usage: /<command> list
  gacha modify:
    description: Modify a gacha chest
    aliases: [gacha m]
    usage: /<command> modify <gacha_name>
  gacha delete:
    description: Delete a gacha
    aliases: [gacha d]
    usage: /<command> delete <gacha_name>
  gacha ticket:
    description: Issue a ticket
    aliases: [gacha t]
    usage: /<command> ticket <player_name>
